=== faintpolecate/Bases-de-datos-Avanzadas/XSD/alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="escuela">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumnos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ID" type="xs:string"></xs:element>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="carrera" type="xs:string"></xs:element>
                                        <xs:element name="promedio" type="xs:double"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== faintpolecate/Bases-de-datos-Avanzadas/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Antonio Ruvalcaba Mata -->

<escuela xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumnos.xsd">
    <alumnos>
        <alumno>
            <ID>01</ID>
            <nombre>Ana</nombre>
            <carrera>INFO</carrera>
            <promedio>9.7</promedio>
        </alumno>
        <alumno>
            <ID>02</ID>
            <nombre>Luis</nombre>
            <carrera>COM</carrera>
            <promedio>7.8</promedio>
        </alumno>
        <alumno>
            <ID>03</ID>
            <nombre>Carlos</nombre>
            <carrera>IMEC</carrera>
            <promedio>9.1</promedio>
        </alumno>
        <alumno>
            <ID>04</ID>
            <nombre>Maria</nombre>
            <carrera>QUIM</carrera>
            <promedio>8.5</promedio>
        </alumno>
        <alumno>
            <ID>05</ID>
            <nombre>Daniel</nombre>
            <carrera>INFO</carrera>
            <promedio>6.0</promedio>
        </alumno>
    </alumnos>
</escuela>
